x-vllm-env: &vllm-env
  HF_HUB_CACHE: "/models"

x-vllm-common: &vllm-common
  image: rocm/pytorch-private:vllm_v0.19.0_jupyternb_apj_media
  working_dir: /workspace
  entrypoint:
    - /bin/bash
  command:
    - -lc
    - >-
      jupyter-lab --allow-root --ip 0.0.0.0 --port 8501 --ServerApp.token='' --ServerApp.password='' --notebook-dir=/workspace/APJ_ROCm_workshop_2026/
  restart: unless-stopped
  ipc: host
  shm_size: 16gb
  group_add:
    - video
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp=unconfined
  devices:
    - /dev/kfd
    - /dev/dri
  environment: *vllm-env

services:
  vllm-8000:
    <<: *vllm-common
    container_name: apj_00
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/00:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "0"
    ports:
      - "8500:8501"

  vllm-8001:
    <<: *vllm-common
    container_name: apj_01
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/01:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "1"
    ports:
      - "8501:8501"

  vllm-8002:
    <<: *vllm-common
    container_name: apj_02
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/02:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "2"
    ports:
      - "8502:8501"
  
  vllm-8003:
    <<: *vllm-common
    container_name: apj_03
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/03:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "3"
    ports:
      - "8503:8501"
  
  vllm-8004:
    <<: *vllm-common
    container_name: apj_04
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/04:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "4"
    ports:
      - "8504:8501"
  
  vllm-8005:
    <<: *vllm-common
    container_name: apj_05
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/05:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "5"
    ports:
      - "8505:8501"
  
  vllm-8006:
    <<: *vllm-common
    container_name: apj_06
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/06:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "6"
    ports:
      - "8506:8501"
  
  vllm-8007:
    <<: *vllm-common
    container_name: apj_07
    volumes:
      - /home/seungrok/APJ_media_workshop/amd-gpu-workshops/docker-compose/07:/workspace
      - /home/amd/models:/models
    environment:
      <<: *vllm-env
      HIP_VISIBLE_DEVICES: "7"
    ports:
      - "8507:8501"

volumes:
  hf-cache:
